### ISSUE TITLE
Update Developer Guide - Use Cases

### ISSUE THREAD

**Issue by dillontkh** [AY2324S2-CS2103T-T17-3/tp#10]
[More details](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#4-update-the-dg-user-stories-glossary-nfrs-use-cases)

**Comment by ruijietay** [comment]
For reference (as per the CS2103 website @dillontkh linked above):
> Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
