### ISSUE TITLE
Task: Create factory method for attributes

### ISSUE THREAD

**Issue by jjchee77** [AY2324S2-CS2103T-T17-3/tp#137]
Currently, validation and sanitization is performed within the various parsers as well as the attribute class itself, some of them are present in one but not the other. This causes code duplication and confusion.

Therefore, there should be a factory method for each attribute responsible for validation and sanitization and ultimately returns an instance of the attribute.

**Comment by dillontkh** [comment]
Changing the type from Enhancement to Task as this appears to have no perceivable difference from the user's POV.

Sounds like it could be appreciated by developers though.
