### ISSUE TITLE
Enhancement: Result display issues

### ISSUE THREAD

**Issue by bgopi23** [AY2324S2-CS2103T-T17-3/tp#139]
Result display is currently scrollable and has long outputs which make it hard to read and forces the user to scroll through the result display in order to read the help message

![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/73015364/c51813dd-0131-4c4b-8c07-d35575291fb4)

Clients returned are crammed together and colon and semicolon are hard to distinguish
![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/73015364/2d1e03fb-3362-4d53-b34e-290720a9a5c2)

**Comment by dillontkh** [comment]
<img width="989" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/f7693080-5fe0-420b-8f0a-a0e38da10f4e">
Response message when editing a client still scrollable

<img width="996" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/06fd8905-3891-42e3-8a02-118797f24cf0">
Same for delete

**Comment by bgopi23** [comment]
> <img width="989" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/f7693080-5fe0-420b-8f0a-a0e38da10f4e">
> 
> Response message when editing a client still scrollable
> 
> 
> 
> <img width="996" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/06fd8905-3891-42e3-8a02-118797f24cf0">
> 
> Same for delete

I think horizontal scrolling is fine for cases like u showed in delete where the information is just too long. If we wrap it and try to fit super long clients and their details within the box it might look messy imo. Another thing we can do is only display certain attributes to prevent overflow. What do u think @dillontkh also my main reason for this enhancement was to prevent vertical scrolling and limit it to 4 lines

**Comment by bgopi23** [comment]
> <img alt="image" width="989" src="https://private-user-images.githubusercontent.com/40649376/315201718-f7693080-5fe0-420b-8f0a-a0e38da10f4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzc3NjUsIm5iZiI6MTcxMTAzNzQ2NSwicGF0aCI6Ii80MDY0OTM3Ni8zMTUyMDE3MTgtZjc2OTMwODAtNWZlMC00MjBiLThmMGEtYTBlMzhkYTEwZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE2MTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Y2Q3MWExOTA5YzVkNDg0ODQyMmE1YWI4ZmJiNzFjOWNhZTM4NmY5ZDQzNzFmZjE4YWU4ZTc3OGNhYWMzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztZOZIV_FyBCt1eDcA5T2AR7pYWYI_FB7QPhuCfqQVs"> Response message when editing a client still scrollable <img alt="image" width="996" src="https://private-user-images.githubusercontent.com/40649376/315201907-06fd8905-3891-42e3-8a02-118797f24cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzc3NjUsIm5iZiI6MTcxMTAzNzQ2NSwicGF0aCI6Ii80MDY0OTM3Ni8zMTUyMDE5MDctMDZmZDg5MDUtMzg5MS00MmUzLThhMDItMTE4Nzk3ZjI0Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE2MTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MmVjZmExMzAzYjEyYWUxMjgyNWRiMTU0YjYzODJiZjRlMTE5NzMyNTAyZTM4OTI0MThmYTBhZDg4MmYxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SmBGxYQ88icAyamwNyD0-kU8SMtXREFjVtpswkEGWog"> Same for delete

thanks, should be resolved now @dillontkh
