### ISSUE TITLE
Task: Trial JAR release

### ISSUE THREAD

**Issue by ruijietay** [AY2324S2-CS2103T-T17-3/tp#163]
Referencing [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week10/project.html#6-do-a-trial-jar-release), we need to release a new trial JAR file for Week 10. 

> [!NOTE]
> We should follow the instructions [here](https://nus-cs2103-ay2324s2.github.io/tp/DevOps.html#making-a-release) on how to do a release (take note the need to update the version).

**Comment by dillontkh** [comment]
rip

**Comment by jjchee77** [comment]
rip
