### ISSUE TITLE
Bug: Fields in detail window get cut off if too long

### ISSUE THREAD

**Issue by dillontkh** [AY2324S2-CS2103T-T17-3/tp#203]
The screenshot below shows a long note, but the same happens if email and address are too long.

Possible solution: Make the area next to the QR code scrollable

![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/afda6dc8-f7e1-45b8-9403-256a60defb9e)

**Comment by jjchee77** [comment]
Has already been added as part of #193
