### ISSUE TITLE
Bug: PersonCard clears after adding/modifying weight

### ISSUE THREAD

**Issue by ruijietay** [AY2324S2-CS2103T-T17-3/tp#217]
PersonCard is cleared after adding/modifying weight is entered as the first command upon startup, as seen in the video below

https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/47778098/29a9b920-93ca-4d93-8d36-50242e11d5a2

**Comment by dillontkh** [comment]
I don't think it's limited to just weight. From my testing, it's the `add` and `edit` commands as well.

**Comment by dillontkh** [comment]
It seems to be an issue carried over from the original AB3. When the `edit` command is run for the first time since the application was opened, the list selection gets cleared. Subsequent `edit`s do not remove the selection.

https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/24f96513-5178-42ec-b6f7-bb1b7d2c44fc

**Comment by jjchee77** [comment]
Commenting out `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` from the `EditCommand.java` class fixes this, you can probably start investigation from there.

Good luck!

**Comment by jjchee77** [comment]
`model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);`

This line of code above causes `newValue` within 

`personListPanel.initListener((observable, oldValue, newValue) -> {
            logger.info("personListPanel changed");
            logger.warning(newValue == null ? "null" : newValue.toString());
            // newValue can be null if the selection in the personListView is cleared
            if (newValue == null) {
                personDetailsPanel.clear();
            } else {
                personDetailsPanel.update(newValue);
            }
        });`
        
in `MainWindow.java` to be null.
