### ISSUE TITLE
Bug: Commands showing incorrect error & help messages

### ISSUE THREAD

**Issue by RyanNgWH** [AY2324S2-CS2103T-T17-3/tp#220]
# Weight
<img width="1293" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/44436551/70b02ac9-5240-40d2-81ea-344e9c19c7e9">

The issue is that the `weight` command no longer uses the `w/` prefix, however it states that the weight value has to be a positive number.

<img width="1296" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/44436551/8a52b844-d2c7-4976-9cd5-358e3836692d">

Help message of the weight command is also not showing the updated command format 

# Find
<img width="1292" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/44436551/5b8d1b3d-c38b-47b4-acba-adabe719e450">
Might be good to mention that prefix for `name` is optional if it is the first argument in the command

**Comment by dillontkh** [comment]
> # Find
> <img alt="image" width="1292" src="https://private-user-images.githubusercontent.com/44436551/318629030-5b8d1b3d-c38b-47b4-acba-adabe719e450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzMzOTEsIm5iZiI6MTcxMjA3MzA5MSwicGF0aCI6Ii80NDQzNjU1MS8zMTg2MjkwMzAtNWI4ZDFiM2QtYzM4Yi00N2I0LWFjYmEtYWRhYmU3MTllNDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1NTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDBkODZmN2ZjMTBmMzdlNTNiYTU5MTUzYTU2N2ZiZThjNzBiNWFlMjAxMjExZTkyOTk2ZWM0ZGRlNDNjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjpQeDxgR8u0Tug72TVwK3Lt3RstTFjxGcimMBEBPNU"> Might be good to mention that prefix for `name` is optional if it is the first argument in the command

I think we should just include that behaviour in the UG, as the 'proper' way is to use the prefix. It also allows the opportunity to 'discover' shortcuts which could feel good for users.

Agree with the weight issues though.

**Comment by bgopi23** [comment]
@RyanNgWH can u elaborate on the weight issues, i dont get it for the first one

**Comment by RyanNgWH** [comment]
@bgopi23 
The weight command now uses the format `weight INDEX VALUE` (does not require the `w/` prefix anymore). The examples and parameters in the help message for the weight command is still using the old format with the `w/` prefix (as shown in the second screenshot).

For the first screenshot, I was thinking that the error message should show an error message such as `invalid command format` if the user uses the old command format with the `w/` prefix. However, I am now thinking that the current error message might still be acceptable since `w/70` would technically be an invalid weight value as shown in the current error message
