### ISSUE TITLE
Bug: Names should accept special characters like '/'

### ISSUE THREAD

**Issue by ruijietay** [AY2324S2-CS2103T-T17-3/tp#233]
<img width="1024" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/47778098/1ca17c4f-6187-4d7c-850b-99331b7fe18f">

**Comment by bgopi23** [comment]
I don't think a we allowed to fix this

**Comment by jjchee77** [comment]
I think its debatable because its technically a bug cause people cannot input their actual name

**Comment by bgopi23** [comment]
@jjchee77 have asked prof lets wait n see

**Comment by jjchee77** [comment]
Oke, thanks!

**Comment by bgopi23** [comment]
cannot be fixed, as confirmed by prof
