### ISSUE TITLE
Bug: Date of weight previously removed weight value remains after edit command.

### ISSUE THREAD

**Issue by ruijietay** [AY2324S2-CS2103T-T17-3/tp#236]
After performing `weight 2 w/` to remove the latest weight from the second client in the list, the date of the recorded weight still remains in the graph. Not sure if this is a bug, otherwise would it be good to specify that this behaviour is correct in the UG?

<img width="1024" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/47778098/b06fee75-f7b2-4235-95bd-fd174ff34799">

**Comment by dillontkh** [comment]
I think it's considered an enhancement, so we can include this behaviour in the UG.

Maybe it could be phrased as a benefit for the user; so that they can quickly tell that a weight has been removed.
