### ISSUE TITLE
[PE-D][Tester D] Missing p/ Flag for Second Example Command for Adding a Client

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-3/tp#250]
![image.png](https://raw.githubusercontent.com/wang-xinrong/ped/main/files/c7610a8a-04b6-4b52-9ff7-5ad1c7152085.png)
The second example command does not work as it missed the phone number field.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: wang-xinrong/ped#3

**Comment by dillontkh** [comment]
update UG to fix example command

**Comment by jjchee77** [comment]
@wang-xinrong

![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/157005277/338081f8-3de4-427c-b7f1-a7aab9798adc)

May I clarify which part of the second example command did not include the phone number field? And why it **did not work**?
Could you further clarify on how to reproduce this bug?
