### ISSUE TITLE
[PE-D][Tester C] UG Documentation: Typo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-3/tp#283]
UG, Page 11, find command, 4th bullet point.
> When an empty input is specified an optional field, only users that have value(s) available for that field will be showed. (e.g.
`find w/` returns all clients that have at least one weight value associated to them).

Perhaps should be:
> When an empty input is specified _for_ an optional field, only _clients_ that have value(s)...

![image.png](https://raw.githubusercontent.com/shaunlxw/ped/main/files/8b99a58b-4daf-4c40-a4aa-b35b927bc940.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: shaunlxw/ped#17

**Comment by dillontkh** [comment]
fix typo in UG

**Comment by bgopi23** [comment]
fixed
