### ISSUE TITLE
[PE-D][Tester B] `weight`: Specifying zero weight deletes the latest weight.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T17-3/tp#287]
Steps to recreate:

1. Person at index 1 with weight values.
2. Run `weight 1 0.0`

Result: latest weight is deleted.

Not a documented feature in the UG so I think this is a bug.

<i><video controls><source src="https://raw.githubusercontent.com/chiaryan/ped/main/files/18783f18-ceed-4c10-a912-52df4ee88dce.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/chiaryan/ped/main/files/18783f18-ceed-4c10-a912-52df4ee88dce.mp4</i>

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chiaryan/ped#7

**Comment by dillontkh** [comment]
mention that using `weight` with 0 will remove the latest weight

`edit`ing height/weight to be 0 will also remove the latest height/weight

mention in UG that height and weight must be > 0
