### ISSUE TITLE
Formatting issues in UG and DG

### ISSUE THREAD

**Issue by RyanNgWH** [AY2324S2-CS2103T-T17-3/tp#377]
<img width="736" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/44436551/bb691ce9-bafc-429c-860d-c820781d9550">

There is a double comma typo in the UG under the examples for `fitadd`

**Comment by ruijietay** [comment]
In addition, under `Logic component` of the DG, there is a typo here 
> All XYZCommandParser classes (e.g., AddCommandParser , DeleteCommandParser , …)
inherit from the Parser interface so that they can be treated similarly where possible
e.g., during testing.

e.g., should be e.g.
