### ISSUE TITLE
Update Developer Guide - User Stories

### ISSUE THREAD

**Issue by dillontkh** [AY2324S2-CS2103T-T17-3/tp#7]
[More details](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#4-update-the-dg-user-stories-glossary-nfrs-use-cases)

**Comment by ruijietay** [comment]
For reference (as per the CS2103 website @dillontkh linked above):
> Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
