### ISSUE TITLE
Bugs in help window

### ISSUE THREAD

**Issue by RyanNgWH** [AY2324S2-CS2103T-T17-3/tp#80]
![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/44436551/aef6e53c-9e46-414b-a99c-7f50120dd367)

- Formatting for `add`, `edit` and `exit` commands are missing whitespace. Description should align with rest of the commands.
- `Open User Guide` button does not seem to be doing anything

**Comment by dillontkh** [comment]
Can confirm the formatting for descriptions is not aligned on Windows.

But on both Windows and Mac the Open User Guide button opens the User Guide in my device's default browser.

**Comment by bgopi23** [comment]
open user guide works for me as well (mac)

**Comment by RyanNgWH** [comment]
Alright thanks for testing! Will re-verify the button functionality on linux again.

Formatting for descriptions seem differ based on OS. Will try to look for a fix.
