### ISSUE TITLE
Update Developer Guide - Non Functional Requirements

### ISSUE THREAD

**Issue by dillontkh** [AY2324S2-CS2103T-T17-3/tp#9]
[More details](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#4-update-the-dg-user-stories-glossary-nfrs-use-cases)

**Comment by ruijietay** [comment]
For reference (as per the CS2103 website @dillontkh linked above):
> Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
