### ISSUE TITLE
Bug: Qr code prematurely deleted on edit command

### ISSUE THREAD

**Issue by jjchee77** [AY2324S2-CS2103T-T17-3/tp#94]
The qr code of a client is currently being prematurely deleted before validation checks are performed during the execution of the `edit` command.

To reproduce this bug, change the name of an existing client 1 to the name of another existing client 2 using the `edit` command.
Then, run the `list` command to refresh the contact list. The qr code will be reflected as empty. Additionally, a new qr code file will be created with existing client 2's name concatenated with existing client 1's number, taking up unnecessary space.

Although the qr code will be re-generated again on app launch (since the relevant info to generate the qr code such as name and phone number is not deleted), this should not be the expected outcome.

The cause of this bug lies in the premature call to `personToEdit.deleteQrCode();` in the `EditCommand.java` file.

![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/157005277/8b035b47-866c-42f8-9a88-36c25ddb7f97)

**Comment by dillontkh** [comment]
I think we're only considering contacts to be same if both name and phone number are the same.

The current code only checks for the same name.

**Comment by jjchee77** [comment]
> I think we're only considering contacts to be same if both name and phone number are the same.
> 
> The current code only checks for the same name.

Yes, I have created #95 to address this. Meanwhile, moving `personToEdit.deleteQrCode();` to after the the duplicate client check would fix the premature deletion, but not the premature creation.
